In [1]:
myDict = {"Fruit_name" : ("Apple","Mango","Banana","Lichu")}

In [2]:
print(myDict)

{'Fruit_name': ('Apple', 'Mango', 'Banana', 'Lichu')}


In [3]:
class Human:
    name = None
    age = None
    def set_name(self):
        self.name = input("Enter Your Name : ")
    def set_age(self):
        self.age = input("Enter Your Age : ")
    def get_name(self):
        print("Your name : "+self.name)
    def get_age(self):
        print("Your age : "+self.age)

In [4]:
person1 = Human()
person1.set_name()
person1.set_age()
person1.get_name()
person1.get_age()

Enter Your Name : Rahul Dey
Enter Your Age : 21
Your name : Rahul Dey
Your age : 21


In [5]:
class Student:
    def __init__(self,name,age,branch):
        self.name = name
        self.age = age
        self.branch = branch
    def details(self):
        print("Name : "+self.name)
        print("Age : "+str(self.age))
        print("Branch : "+self.branch)

In [6]:
S1 = Student("Rahul Dey",21,"CSE")
S1.details()

Name : Rahul Dey
Age : 21
Branch : CSE


In [7]:
# Single level Inheritance in python
class fruit():
    def __init__(self):
        print("Fruit Class")
        
class Mango(fruit):
    def __init__(self):
        super().__init__()
        print("Mango Class")
        
m1 = Mango()

Fruit Class
Mango Class


In [9]:
import numpy as np
# 1-D array
a = np.array([1,2,3])
print(a)
# 2-D array
d = np.array([[1,2,3],
             [4,5,6]])
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [10]:
# 5*5 numpy array comprising of all zeros
b = np.zeros((5,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# add 2 numpy array
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.sum((a1,a2),axis=0)) # add column wise
print(np.sum((a1,a2),axis=1)) # add row wise

[5 7 9]
[ 6 15]
